Repository modelscope/Trinity-RFT, pull requests merged in 2025-04, with the labels that each got.

#1 Add GitHub Actions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pre-commit.yaml
  .github/workflows/sphinx-doc.yaml
  docs/sphinx_doc/source/conf.py
Labels: documentation, testcase

#3 Try to activate data module in the launcher
  docs/sphinx_doc/source/tutorial/example_data_functionalities.md
  docs/sphinx_doc/source/tutorial/example_reasoning_advanced.md
  trinity/cli/launcher.py
Labels: enhancement

#5 Fix Sphinx doc
  README.md
  docs/sphinx_doc/Makefile
  docs/sphinx_doc/_templates/package.rst_t
  docs/sphinx_doc/assets/opmd.pdf
  docs/sphinx_doc/build_doc.sh
  docs/sphinx_doc/source/conf.py
  docs/sphinx_doc/source/index.rst
  docs/sphinx_doc/source/main.md
  docs/sphinx_doc/source/tutorial/example_data_functionalities.md
  docs/sphinx_doc/source/tutorial/example_multi_turn.md
  docs/sphinx_doc/source/tutorial/example_reasoning_advanced.md
  docs/sphinx_doc/source/tutorial/trinity_programming_guide.md
  pyproject.toml
  trinity/common/experience.py
  trinity/explorer/__init__.py
  trinity/manager/__init__.py
  trinity/trainer/__init__.py
Labels: documentation

#17 Fix unittest action
  .github/workflows/docker/docker-compose.yaml
  .github/workflows/unittest.yaml
  pyproject.toml
Labels: bug

#13 Add training service
  environments/data.yaml
  environments/env_mapping.json
  environments/training.yaml
  pyproject.toml
  scripts/install.py
  scripts/start_servers.py
  trinity/cli/client.py
  trinity/cli/launcher.py
  trinity/cli/server.py
  trinity/common/config.py
  trinity/data/controllers/default_ops.py
  trinity/data/core/dataset_db.py
  trinity/data/readme.md
  trinity/data/server.py
Labels: enhancement
